trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    sudo apt install openjfx
    sudo apt purge openjfx
    sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
    sudo apt-mark hold openjfx libopenjfx-jni libopenjfx-java
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
