trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo add-apt-repository ppa:linuxuprising/java
    sudo apt-get update
    sudo apt-get -y install oracle-java10-set-default
  displayName: 'Install Oracle JDK 10 as Default'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
